spring:
  data:
    mongodb:
      auto-index-creation: false
      database: COMMERCE
      uri: mongodb://localhost:27017/?authSource=admin&readPreference=primary&ssl=false
  datasource:
    url: jdbc:mysql://localhost:3306/commerce
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: 1234
